# Generated by Django 4.1.1 on 2022-11-23 13:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, help_text="What's the name of this country?", max_length=500)),
                ('continent', models.CharField(blank=True, choices=[('Asia', 'Asia'), ('Africa', 'Africa'), ('Europe', 'Europe'), ('Australia', 'Australia'), ('Antartica', 'Antartica'), ('North America', 'North America'), ('South America', 'South America')], help_text='What continent is this country in?', max_length=500)),
                ('country_code', models.CharField(blank=True, help_text='The country name code, e.g NG.', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, help_text='The name of this degree', max_length=500)),
                ('code', models.CharField(blank=True, help_text='The associated degree code, like B.Sc', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Degrees',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, help_text='The name of the department', max_length=500)),
                ('duration', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], help_text='The number of years it takes to graduate from this department ', max_length=10)),
                ('code', models.CharField(blank=True, help_text='The associated department code, like ECE', max_length=50)),
                ('degree', models.ManyToManyField(help_text='The type of degree offered by this department.', to='academia.degree')),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='The name of the Faculty', max_length=500)),
                ('departments', models.ManyToManyField(blank=True, editable=False, related_name='faculty_departments', to='academia.department')),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('listed', models.BooleanField(default=True, help_text='Tick to indicate no longer valid and will not be returned in API calls.')),
                ('type', models.CharField(choices=[('university', 'university'), ('polytechnic', 'polytechnic'), ('monotechnic', 'monotechnic'), ('college', 'college')], help_text='The type of higher intitution.', max_length=20)),
                ('name', models.CharField(blank=True, help_text='The name of the school.', max_length=500)),
                ('code', models.CharField(blank=True, help_text='The asociated school short code, e.g Unizik.', max_length=50)),
                ('country', models.ManyToManyField(blank=True, related_name='school_country', to='academia.country')),
                ('departments', models.ManyToManyField(blank=True, editable=False, related_name='child_departments', to='academia.department')),
                ('faculties', models.ManyToManyField(blank=True, editable=False, related_name='child_faculties', to='academia.faculty')),
            ],
            options={
                'verbose_name_plural': 'Schools',
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_school', to='academia.school'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_faculty', to='academia.faculty'),
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_school', to='academia.school'),
        ),
        migrations.AddField(
            model_name='country',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='country_schools', to='academia.school'),
        ),
    ]
