# Generated by Django 4.1.1 on 2022-11-17 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="What's the name of this country?", max_length=500)),
                ('continent', models.CharField(blank=True, help_text='What continent is this country in?', max_length=500)),
                ('country_code', models.CharField(blank=True, help_text='The country name code, e.g NG.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The name of the department', max_length=500)),
                ('degree', models.CharField(blank=True, help_text='The type of degree offered by this department.', max_length=500)),
                ('duration', models.IntegerField(blank=True, help_text='The duration taken to graduate from this department ')),
                ('code', models.CharField(blank=True, help_text='The associated department code, like ECE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The name of the Faculty', max_length=500)),
                ('departments', models.ManyToManyField(related_name='faculty_departments', to='academia.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('university', 'university'), ('polytechnic', 'polytechnic'), ('monotechnic', 'monotechnic'), ('college', 'college')], help_text='The type of higher intitution.', max_length=20)),
                ('code', models.CharField(blank=True, help_text='The asociated school short code, e.g Unizik.', max_length=50)),
                ('name', models.CharField(blank=True, help_text='The name of the school.', max_length=500)),
                ('listed', models.BooleanField(default=True, help_text='Tick to indicate no longer valid and will not be returned in API calls.')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academia.country')),
                ('departments', models.ManyToManyField(related_name='child_departments', to='academia.departments')),
                ('faculties', models.ManyToManyField(related_name='child_faculties', to='academia.faculties')),
            ],
        ),
        migrations.AddField(
            model_name='faculties',
            name='school',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_school', to='academia.schools'),
        ),
        migrations.AddField(
            model_name='departments',
            name='faculty',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_faculty', to='academia.faculties'),
        ),
        migrations.AddField(
            model_name='departments',
            name='school',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_school', to='academia.schools'),
        ),
    ]
