# Generated by Django 4.1.1 on 2022-11-17 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.CharField(blank=True, choices=[('Asia', 'Asia'), ('Africa', 'Africa'), ('Europe', 'Europe'), ('Australia', 'Australia'), ('Antartica', 'Antartica'), ('North America', 'North America'), ('South America', 'South America')], help_text='What continent is this country in?', max_length=500),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='departments',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='schools',
            name='country',
        ),
        migrations.AlterField(
            model_name='schools',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='child_departments', to='academia.departments'),
        ),
        migrations.AlterField(
            model_name='schools',
            name='faculties',
            field=models.ManyToManyField(blank=True, related_name='child_faculties', to='academia.faculties'),
        ),
        migrations.AlterField(
            model_name='schools',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='schools',
            name='country',
            field=models.ManyToManyField(blank=True, null=True, related_name='school_country', to='academia.country'),
        ),
    ]
