# Generated by Django 4.1.1 on 2022-11-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, default='logo.png', help_text='The logo of this institution', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='school',
            name='owned_by',
            field=models.CharField(blank=True, choices=[('Federal', 'Federal'), ('State', 'State')], default='None', help_text="If it's a Public intitution, is it federal owned or state owned?", max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='ownership',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='None', help_text='The ownership status of this intitution, is it public or private?', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, help_text='The website of this institution', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('University', 'University'), ('Polytechnic', 'Polytechnic'), ('Monotechnic', 'Monotechnic'), ('College', 'College')], help_text='The type of higher intitution.', max_length=20),
        ),
    ]
