# Generated by Django 4.1.1 on 2022-11-17 13:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_alter_country_continent_alter_country_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, help_text='The name of the department', max_length=500)),
                ('degree', models.CharField(blank=True, help_text='The type of degree offered by this department.', max_length=500)),
                ('duration', models.IntegerField(blank=True, help_text='The duration taken to graduate from this department ')),
                ('code', models.CharField(blank=True, help_text='The associated department code, like ECE', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='The name of the Faculty', max_length=500)),
                ('departments', models.ManyToManyField(blank=True, related_name='faculty_departments', to='academia.department')),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('listed', models.BooleanField(default=True, help_text='Tick to indicate no longer valid and will not be returned in API calls.')),
                ('type', models.CharField(choices=[('university', 'university'), ('polytechnic', 'polytechnic'), ('monotechnic', 'monotechnic'), ('college', 'college')], help_text='The type of higher intitution.', max_length=20)),
                ('name', models.CharField(blank=True, help_text='The name of the school.', max_length=500)),
                ('code', models.CharField(blank=True, help_text='The asociated school short code, e.g Unizik.', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Schools',
            },
        ),
        migrations.RemoveField(
            model_name='faculties',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='faculties',
            name='school',
        ),
        migrations.RemoveField(
            model_name='schools',
            name='country',
        ),
        migrations.RemoveField(
            model_name='schools',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='schools',
            name='faculties',
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Faculties',
        ),
        migrations.DeleteModel(
            name='Schools',
        ),
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.ManyToManyField(blank=True, related_name='school_country', to='academia.country'),
        ),
        migrations.AddField(
            model_name='school',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='child_departments', to='academia.department'),
        ),
        migrations.AddField(
            model_name='school',
            name='faculties',
            field=models.ManyToManyField(blank=True, related_name='child_faculties', to='academia.faculty'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_school', to='academia.school'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_faculty', to='academia.faculty'),
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_school', to='academia.school'),
        ),
    ]
