# Generated by Django 4.1.1 on 2022-11-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_school_logo_school_owned_by_school_ownership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='founded',
            field=models.IntegerField(blank=True, default='0000', null=True),
        ),
    ]
