# Generated by Django 4.1.1 on 2022-11-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_school_founded'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(help_text="Where's this school located?", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(help_text='The asociated school short code, e.g Unizik.', max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='founded',
            field=models.IntegerField(default='0000', help_text='What year was this school founded?', null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(default='logo.png', help_text='The logo of this institution', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(help_text='The name of the school.', max_length=500),
        ),
        migrations.AlterField(
            model_name='school',
            name='owned_by',
            field=models.CharField(choices=[('Federal', 'Federal'), ('State', 'State')], default='None', help_text="If it's a Public intitution, is it federal owned or state owned?", max_length=20),
        ),
    ]
