# Generated by Django 4.1.1 on 2022-11-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_school_address_alter_school_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, help_text="Where's this school located?", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.ManyToManyField(related_name='school_country', to='academia.country'),
        ),
    ]
