# Generated by Django 4.1.1 on 2023-01-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_alter_school_address_alter_school_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='owned_by',
            field=models.CharField(choices=[('Private', 'Private'), ('Federal', 'Federal'), ('State', 'State')], default='None', help_text="If it's a Public intitution, is it federal owned or state owned?", max_length=20),
        ),
    ]
