# Generated by Django 4.1.1 on 2023-01-20 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academia", "0006_alter_school_owned_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="country",
        ),
        migrations.AddField(
            model_name="school",
            name="country",
            field=models.ForeignKey(
                default="cc4a70fb-d7c3-4f01-8613-cb08b3a91912",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="school_country",
                to="academia.country",
            ),
            preserve_default=False,
        ),
    ]
