# Generated by Django 4.1.1 on 2023-01-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0007_remove_school_country_school_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='schools',
            field=models.ManyToManyField(blank=True, editable=False, related_name='country_schools', to='academia.school'),
        ),
    ]
