# Generated by Django 4.1.1 on 2023-03-02 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0008_alter_country_schools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='degree',
        ),
        migrations.AddField(
            model_name='department',
            name='degree',
            field=models.ForeignKey(default='', help_text='The type of degree offered by this department.', on_delete=django.db.models.deletion.CASCADE, to='academia.degree'),
        ),
    ]
