# Generated by Django 4.1.1 on 2023-03-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0009_remove_department_degree_department_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(blank=True, help_text='The country name code in uppercase only, e.g NG.', max_length=50),
        ),
    ]
