# Generated by Django 4.1.1 on 2023-03-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0010_alter_country_country_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['id', 'name', 'degree'], name='academia_de_id_63e4ea_idx'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['school', 'name', 'id'], name='academia_fa_school__806783_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['name', 'code', 'country', 'type', 'founded', 'ownership', 'owned_by', 'address', 'website', 'id'], name='academia_sc_name_031369_idx'),
        ),
    ]
