# Generated by Django 4.1.1 on 2023-04-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0011_department_academia_de_id_63e4ea_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='listed',
        ),
        migrations.AddField(
            model_name='school',
            name='unlisted',
            field=models.BooleanField(default=True, help_text='Tick to indicate no longer valid and this school will not be returned in API Response, untick to include in API Response'),
        ),
    ]
