# Generated by Django 4.1.1 on 2023-05-16 21:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("rest_framework_api_key", "0005_auto_20220110_1102"),
        ("academia", "0013_alter_school_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("developer", "Developer"),
                            ("organisation", "Organisation"),
                        ],
                        max_length=25,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "clients",
            },
        ),
        migrations.CreateModel(
            name="ClientAPIKey",
            fields=[
                (
                    "apikey_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="rest_framework_api_key.apikey",
                    ),
                ),
                (
                    "rate",
                    models.BigIntegerField(
                        default=50,
                        help_text="Default throttle rate for requests per hour.",
                    ),
                ),
                (
                    "expiry_time",
                    models.CharField(
                        choices=[
                            ("30", "Thirty Days"),
                            ("60", "Sixty Days"),
                            ("90", "Ninty Days"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_key",
                        to="academia.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clients API Key",
                "verbose_name_plural": "Clients API Key(s)",
                "db_table": "clients_apikey",
            },
            bases=("rest_framework_api_key.apikey",),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["id", "email", "client_type"], name="clients_id_f1f4a8_idx"
            ),
        ),
    ]
