# Generated by Django 4.1.1 on 2023-05-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia", "0015_alter_client_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientapikey",
            name="scope",
            field=models.SlugField(default="govahq", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
