# Generated by Django 4.1.1 on 2023-05-18 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0016_clientapikey_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientapikey',
            name='expiry_time',
            field=models.CharField(choices=[('30', 'Thirty Days'), ('60', 'Sixty Days'), ('90', 'Ninty Days')], default=django.utils.timezone.now, max_length=2),
        ),
    ]
