# Generated by Django 4.1.1 on 2023-05-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia", "0016_clientapikey_scope"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientapikey",
            name="expiry_time",
        ),
        migrations.AlterField(
            model_name="clientapikey",
            name="scope",
            field=models.SlugField(
                blank=True, editable=False, max_length=100, unique=True
            ),
        ),
    ]
