# Generated by Django 4.1.1 on 2023-05-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0017_alter_clientapikey_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientapikey',
            name='expiry_time',
            field=models.CharField(choices=[('30', 'Thirty Days'), ('60', 'Sixty Days'), ('90', 'Ninty Days')], max_length=2),
        ),
    ]
