# Generated by Django 4.1.1 on 2023-05-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0017_remove_clientapikey_expiry_time_and_more'),
        ('academia', '0019_alter_clientapikey_rate'),
    ]

    operations = [
    ]
