# Generated by Django 4.1.1 on 2023-06-25 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0020_merge_20230520_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('organization', models.CharField(max_length=200)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='academia.school')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField()),
                ('degree_type', models.CharField(max_length=100)),
                ('prerequisites', models.TextField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.school')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=10000)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField()),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.accreditationbody')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.school')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='ranking',
            field=models.ManyToManyField(blank=True, related_name='school_ranking', to='academia.ranking'),
        ),
    ]
