name: Univast CI

on:
  pull_request:
    branches: ["main"]

env:
  DJANGO_ALLOWED_HOSTS: "0.0.0.0,127.0.0.1"
  UNIVAST_DB_NAME: "value"
  UNIVAST_DB_USER: "value"
  UNIVAST_DB_PASSWORD: "value"
  UNIVAST_DB_HOST: "value"
  UNIVAST_DB_PORT: "value"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        run: python manage.py migrate
      - name: Run Tests
        run: |
          python manage.py test
