# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - univastapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://univast.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3ef160c54740460886d03f9aa09ab94d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3aed25ef80da451a9d6cb74bd71d154b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: univast.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3ef160c54740460886d03f9aa09ab94d }}/univastapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'univastapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1708b579d7ae450dbefc15f8414e3f2d }}
        images: 'univast.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3ef160c54740460886d03f9aa09ab94d }}/univastapi:${{ github.sha }}'